### ISSUE TITLE
Refactor swarming into standalone library

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic-legacy#1236]
The swarming code is tightly coupled to the OPF but could be very useful elsewhere. It should be a library that has two main operations for a set of permute objects - ask for new parameter set, and give a score for a previously given parameter set.

The design hasn't been fully aligned with the current codebase. The current codebase makes assumptions throughout that tie it to the OPF and DAO. It is really important that we don't have regressions in functionality and it will likely be a pretty significant initiative to organize the code in a way so that we retain existing OPF swarming functions while providing an interface for other clients.

---
- [x] [Investigate what tasks are necessary to complete swarming as a library](https://github.com/numenta/nupic/issues/1753)
- [x] Create sub-tasks here from work in https://github.com/numenta/nupic/issues/1753
- [x] [Hypersearch Decoupling Milestone 1: Separate swarming code into core Hypersearch files and NuPIC-specific Client ](https://github.com/numenta/nupic/issues/2391)
- [ ] [Hypersearch Decoupling Milestone 2: Define the Hypersearch API ](https://github.com/numenta/nupic/issues/2393)
- [ ] [Hypersearch Decoupling Milestone 3: Migrate Hypersearch API to new design ](https://github.com/numenta/nupic/issues/2394)
- [ ] [Hypersearch Decoupling Milestone 4: Deploy Hypersearch to its own PyPI project and include in NuPIC requirement.txt ](https://github.com/numenta/nupic/issues/2395)
- [ ] [Hypersearch Decoupling Milestone 5: Move Hypersearch out of NuPIC into stand-alone repo ](https://github.com/numenta/nupic/issues/2396)

**Comment by rhyolight** [comment]
As we talked about in our [last review meeting](https://www.youtube.com/watch?v=9Bkt-OC2vV8), this issue has been moved into milestone 0.3. The title needs to be updated and more granular subtasks should be created. @scottpurdy, please update the title of this ticket accordingly.

**Comment by breznak** [comment]
pasting a relevant comment by @rcrowder 

>I wonder whether parameter tuning could interface to existing packages that do a similar job, such as Neurofitter (http://www.ncbi.nlm.nih.gov/pubmed/18974796?dopt=Abstract&holding=f1000,f1000m,isrctn). Maybe NeRvolver, http://www.biomedcentral.com/1471-2202/13/S1/P36 Interfacing with HTM maybe a large a hurdle that isn't necessary, but good to see how others have approached this issue.
_
I like the idea of lifting exiting machine learning to assist swarming. At some point I also want to try using an auto-encoder between the sensory stream and SP/TP encoder.
_
Links taken from; CNS 2014 Tutorial - Neuronal Model Parameter Search Techniques (http://www.cnsorg.org/cns-2014-tutorials#t9paramsearch)

**Comment by scottpurdy** [comment]
There are some features in Hypersearch that are pretty important, like the ability to quickly select the fields that need to be included (which is usually a small subset when you have many fields). I doubt a third party library will give us the flexibility that we need.

**Comment by breznak** [comment]
> like the ability to quickly select the fields that need to be included (which is usually a small subset when you have many fields) 

Well, I think quickly `grounding` some (select) fields is not an uncommon technique, so I believe it should be available in some `parameter optimization tools` (not that I've looked though)

**Comment by oxtopus** [comment]
:+1: for decoupling swarming and OPF.  As we move swarming into a separate standalone package, I'd like to take it a bit further and advocate for decoupling from nupic entirely.  Certainly, `hypersearch` will regard users of `nupic` as its first, and most important user, but I think we'll get the most out of this effort by completely separating out the concerns.  With a well-documented API, `nupic` need only implement the `nupic`-specific components that plug into a generalized hypersearch workflow.

**Comment by cogmission** [comment]
👍

**Comment by scottpurdy** [comment]
@mihail911
