### ISSUE TITLE
General Build Improvements

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1429]
We want to clean up our builds and make the `nupic.core` build more separate from the `nupic` build. We currently have a `CMakeLists.txt` file in each repository, but it seems like it should only be in `nupic.core`, and then the `nupic` build should just put the `nupic.core` binary in the right place and run on top of it. 

We also need to create a proper CMake style guide and make sure we're adhering to it. 

---
- [ ] [Create a CMake style guide](https://github.com/numenta/nupic.core/issues/205)
- [ ] [Adhere to CMake Style Guide](https://github.com/numenta/nupic.core/issues/206)
- [ ] [PIL depends on libtiff.so.5, which is not installed](https://github.com/numenta/nupic-linux64/issues/28)
- [ ] [remove PIL from the repo (deprecated by Pillow)](https://github.com/numenta/nupic-linux64/issues/13)
