### ISSUE TITLE
Update Builds to C++ 11

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1445]
We've decided to upgrade to C++ 11. This means updating both `nupic` and `nupic.core` builds to the C++ 11 standard. 

---
- [x] [C++11 standard transform](https://github.com/numenta/nupic.core/pull/177) (`nupic.core`)
- [x] [Update SWIG to version with C++11 support](https://github.com/numenta/nupic/issues/1417)
- [x] [Provide pcre and yamp-cpp dependencies](https://github.com/numenta/nupic-linux64/issues/31) (linux64)
- [x] [Provide pcre and yamp-cpp dependencies](https://github.com/numenta/nupic-darwin64/issues/13) (darwin64)
- [x] [Revert installation of pcre and yaml-cpp from ci scripts](https://github.com/numenta/nupic/issues/1446)
- [x] [Switch build to C++11](https://github.com/numenta/nupic.core/issues/178) (`nupic.core`)
- [x] [Switch build to C++11](https://github.com/numenta/nupic/issues/1485) (`nupic`)
