### ISSUE TITLE
General Alpha Bug Fixes

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1463]
A list of bugs that should be fixed.

---
- [ ] [C++ and Py implementations of SpatialPooler differ in produced SDRs](https://github.com/numenta/nupic/issues/1352)
- [ ] [adds new SP compatibility test (currently failing)](https://github.com/numenta/nupic/pull/1351)
- [ ] [CLAModel init fails when called with default parameters](https://github.com/numenta/nupic/issues/1307)
- [ ] [Anomaly ignoring unfulfilled predictions](https://github.com/numenta/nupic/issues/1300)
- [ ] [Unable to generate build scripts!](https://github.com/numenta/nupic.core/issues/214)
