### ISSUE TITLE
General New Alpha Features

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1464]
This lists any general new features to be added in Alpha. 

---
- [ ] [Pass input value from Anomaly to AnomalyLikelihood](https://github.com/numenta/nupic/issues/967)
- [ ] [Expose Anomaly's parameters to OPF, so it can be used in swarming](https://github.com/numenta/nupic/issues/1305)
- [x] [Augment monitor mixin framework](https://github.com/numenta/nupic/issues/1459)
- [ ] [Add test for "decomposability" for SDRs by Spatial Pooler](https://github.com/numenta/nupic/issues/1319)
- [ ] [GeospatialCoordinateEncoder should allow optional altitude](https://github.com/numenta/nupic/issues/1461)
- [ ] [Log Encoder should be a subclass of Scalar Encoder](https://github.com/numenta/nupic/issues/544)
- [ ] [Clear output vector before passing to encoder](https://github.com/numenta/nupic/issues/981)
- [ ] [Refactor common logic in encoders to base class](https://github.com/numenta/nupic/issues/947)
