### ISSUE TITLE
Create a pure C++ implementation of Temporal Memory: Phase 1

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1470]
Issues for creating the interim data structures necessary for TM in C++.

---
- [x] [Implement new C++ data structure to power algorithms](https://github.com/numenta/nupic.core/issues/216)
- [x] [Interface with new C++ data structure to power algorithms](https://github.com/numenta/nupic/issues/1468)
- [x] [Create a Temporal Memory implementation that uses C++ Connections](https://github.com/numenta/nupic/issues/1507)
