### ISSUE TITLE
nupic should build assuming nupic.core is a standard external library

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1483]
The `nupic.core` build should result in a C library that can be put into the system path for the `nupic` build to use. This should allow us to remove cmake from `nupic` altogether and use a pure setuptools build and installation. 

The nupic build will build the Python bindings, and treat nupic.core as an external library. It will not build nupic.core. It will only rely on the nupic.core release (include, bin, lib) and a git checkout is not needed. The nupic build will expect the release to be in standard places. A standard install into system paths will be handled automatically. For non-standard installs the user can set environment variables (e.g. include path) just like any other C project. You will also be able to specify a particular directory for the nupic.core install as an argument to the nupic build. 

Here is some psuedocode the describes the imagined build logic:

```
determine nupic.core include/lib path and nupic install path (default to standard locations, overridable by user)

get SHA or version of expected nupic.core (could be NULL for "take anything” or “HEAD")

if nupic.core NOT in include/lib path:
  if archive available for SHA or version and this platform:
    download archive
  else:
    git clone nupic.core at specified SHA or version tag
    build nupic.core from source
  install nupic.core library in specified install path

validate expected nupic.core SHA/version through API
if not valid throw build error
build nupic in build/ directory
install into nupic install path
```

---
- [x] [SHA/version of nupic.core will be exposed in the header file as part of the API](https://github.com/numenta/nupic.core/issues/225) (@oxtopus)
- [x] [nupic.core is installable as a standalone library](https://github.com/numenta/nupic.core/issues/77) (@oxtopus)
- [x] [nupic.core standalone binary file is available by SHA on S3](https://github.com/numenta/nupic.core/issues/202) (@rhyolight)
- [x] [NuPIC downloads and uses nupic.core binary during installation if necessary](https://github.com/numenta/nupic/issues/1421) (@rhyolight)
- [x] [NuPIC build validate's nupic.core version through its API](https://github.com/numenta/nupic/issues/1489) (@oxtopus)
