### ISSUE TITLE
Transfer "HtmTests" out of NuPIC and into nupic.core

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic-legacy#1619]
This requires:

---
- [ ] [Transfer cpp_region from nupic to nupic.core](https://github.com/numenta/nupic.core/issues/254)
- [ ] [Move py_support from nupic to nupic.core](https://github.com/numenta/nupic.core/issues/256)
- [ ] [Add HtmTest to nupic.core](https://github.com/numenta/nupic.core/issues/255)
- [ ] [Remove HtmTests from NuPIC](https://github.com/numenta/nupic/issues/1620)
